CREATE TABLE user_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(320) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(50) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  CONSTRAINT chk_user_accounts_role
    CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE cars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  make VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  image_url VARCHAR(2048),
  review_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  owner_id BIGINT,
  CONSTRAINT fk_cars_owner
    FOREIGN KEY (owner_id) REFERENCES user_accounts(id),
  CONSTRAINT chk_cars_review_status
    CHECK (review_status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_cars_review_status
  ON cars(review_status);

CREATE INDEX idx_cars_owner_id
  ON cars(owner_id);

CREATE TABLE image_assets (
  id UUID PRIMARY KEY,
  storage_path VARCHAR(255) NOT NULL UNIQUE,
  content_type VARCHAR(100) NOT NULL,
  owner_id BIGINT NOT NULL,
  CONSTRAINT fk_image_assets_owner
    FOREIGN KEY (owner_id) REFERENCES user_accounts(id)
);

CREATE INDEX idx_image_assets_owner_id
  ON image_assets(owner_id);
