spring.application.name=world-garage-backend

spring.datasource.url=jdbc:h2:file:./data/worldgarage
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=${WORLD_GARAGE_ADMIN_USERNAME:admin}
spring.security.user.roles=ADMIN